# Generated by Django 4.2.13 on 2026-05-18 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар')),
                ('bio', models.TextField(blank=True, verbose_name='О себе')),
                ('title', models.CharField(blank=True, help_text='Например: Frontend Developer', max_length=200, verbose_name='Роль/Специализация')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Город')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
                ('telegram', models.CharField(blank=True, max_length=100, verbose_name='Telegram')),
                ('github', models.URLField(blank=True, verbose_name='GitHub')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('website', models.URLField(blank=True, verbose_name='Сайт')),
                ('skills_summary', models.TextField(blank=True, verbose_name='Краткое описание навыков')),
                ('is_available', models.BooleanField(default=False, verbose_name='Доступен для работы/проектов')),
                ('theme_preference', models.CharField(choices=[('light', 'Светлая'), ('dark', 'Тёмная')], default='light', max_length=10, verbose_name='Тема оформления')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
    ]
